version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: testdb
      DB_HOST: db
      DB_PORT: "5432"
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
